### ISSUE TITLE
Create Navigation Bar

### ISSUE THREAD

**Issue by buccatm** [campus-occupancy/campus-occupancy#1]
Please do work for this task in a branch called issue-1.

- [x]  Have the nave bar display the links add data and edit, sign out when logged in

- [x] Make the logo take the user to the landing page when not logged in

- [x] Make logo take the user to the home page when logged in

- [x] remove the login from nav

**Comment by CalianaFortin** [comment]
![image](https://user-images.githubusercontent.com/70739998/99630498-1c58eb00-29de-11eb-92e4-c806ca5affa6.png)
