### ISSUE TITLE
Up-to-date screenshots showing the state of the project in GitHub organization.

### ISSUE THREAD

**Issue by buccatm** [campus-occupancy/campus-occupancy#13]
Please do work for this task in a branch named issue-013

- [x] Add the new images of the landing page, the add data page,edit data page, and login page

**Comment by CalianaFortin** [comment]
![Screenshot_2020-11-18 Table of contents](https://user-images.githubusercontent.com/70739998/99636880-25e75080-29e8-11eb-98fc-58d92f6e7967.jpg)
