### ISSUE TITLE
Create Login Page

### ISSUE THREAD

**Issue by buccatm** [campus-occupancy/campus-occupancy#2]
Please do work for this task in a branch called issue-2.

- [x] use the template login

- [x]  figure out how to improve the page

- [x] Try changing the background

- [x] Add a new Header called Log in

- [x]  Change the position for password and user name text

**Comment by CalianaFortin** [comment]
![image](https://user-images.githubusercontent.com/70739998/99630937-ccc6ef00-29de-11eb-827d-9ec764fe080d.png)
