### ISSUE TITLE
Implement the Import  Page

### ISSUE THREAD

**Issue by fredstraub** [campus-occupancy/campus-occupancy#27]
Please do work for this task in a branch called issue-27.

This issue is dependent on the mapping application and the collection schema naming to be complete.

- [x] Able to add Data by uploading files cvs

**Comment by CalianaFortin** [comment]
I believe the edit data page is finished for now all we need to do is continue to add csv files to the default data set 
![Screenshot_2020-12-06 University of Hawaii Campus Occupancy](https://user-images.githubusercontent.com/70739998/101281158-a7bdd480-3771-11eb-93ed-a664de21da06.png)
I think the edit data page was supposed to just display data which I already did
