### ISSUE TITLE
Create Footer

### ISSUE THREAD

**Issue by buccatm** [campus-occupancy/campus-occupancy#3]
Please do work for this task in a branch called issue- 003.

- [x] change the color 

- [x] add basic info

**Comment by fredstraub** [comment]
Edited/updated footer component information. Ran lint on the code prior to merge.
<img width="1813" alt="Landing-Page-with-old-footer-navbar" src="https://user-images.githubusercontent.com/50086431/99613801-574a2700-29bc-11eb-844a-9919688bdf7a.png">
Old Footer
![Landing-page-with-new-footer-old-navbar](https://user-images.githubusercontent.com/50086431/99613825-64ffac80-29bc-11eb-99a5-cc3f0b62a82e.png)
<img width="1684" alt="ES Lint on footer jsx" src="https://user-images.githubusercontent.com/50086431/99613892-7ea0f400-29bc-11eb-94d8-02b587cb7006.png">
