### ISSUE TITLE
Create and implement Density Collection

### ISSUE THREAD

**Issue by fredstraub** [campus-occupancy/campus-occupancy#32]
Please do work for this task in a branch called issue-32.  Create and implement the collection named density which will be from the data sets that give the population density sourced from the HAAC2020 data. Retain the naming schema of the mapping application.

**Comment by CalianaFortin** [comment]
Implemented the asset collection to be used for the add data page.

**Comment by CalianaFortin** [comment]
<img width="836" alt="Screen Shot 2020-12-03 at 1 55 24 PM" src="https://user-images.githubusercontent.com/70739998/101104452-3c0c1980-356f-11eb-9888-60a62cd45feb.png">

**Comment by CalianaFortin** [comment]
This issue is not completed yet because the default JSON file has to be added to the private folder. For now, I have a JSON file I loaded by default however, this needs to be changed.

**Comment by CalianaFortin** [comment]
![Screenshot_2020-12-06 University of Hawaii Campus Occupancy](https://user-images.githubusercontent.com/70739998/101281074-3aaa3f00-3771-11eb-9ea5-6ccba9af69d6.png)
<img width="1401" alt="Screen Shot 2020-12-06 at 3 12 24 AM" src="https://user-images.githubusercontent.com/70739998/101281078-40078980-3771-11eb-8c09-b8a4c05f02fa.png">
