### ISSUE TITLE
Fix the Styling in Import Data

### ISSUE THREAD

**Issue by fredstraub** [campus-occupancy/campus-occupancy#34]
Please do work for this task in a branch called issue-34.  Allow the users to upload .csv files (kinda done in Tasks/LoadBuildingTask.js

**Comment by CalianaFortin** [comment]
<img width="1422" alt="Screen Shot 2020-12-16 at 10 49 07 PM" src="https://user-images.githubusercontent.com/70739998/102465167-6ccd6380-3ff1-11eb-94d2-00f3ebdf7150.png">
