### ISSUE TITLE
Create Geojson File

### ISSUE THREAD

**Issue by buccatm** [campus-occupancy/campus-occupancy#4]
Please do work for this task in a branch called issue- 004.

- [x] use geojson.io to make a map of UH

**Comment by CalianaFortin** [comment]
<img width="887" alt="Screen Shot 2020-11-18 at 8 41 56 PM" src="https://user-images.githubusercontent.com/70739998/99630778-8a051700-29de-11eb-9228-0c4db906a8b8.png">
<img width="950" alt="Screen Shot 2020-11-18 at 8 41 49 PM" src="https://user-images.githubusercontent.com/70739998/99630781-8b364400-29de-11eb-8654-947e16f580d1.png">
