### ISSUE TITLE
Create Landing Page Body

### ISSUE THREAD

**Issue by buccatm** [campus-occupancy/campus-occupancy#5]
Please do work for this task in a branch called issue- 005.

- [x] Have the background be the map

- [x] Create the Header with the Green background

- [x]  Add the Login button bellow header

- [x] Give button Animation

- [x]  Have button take the user to login page

**Comment by CalianaFortin** [comment]
![image](https://user-images.githubusercontent.com/70739998/99630292-b2404600-29dd-11eb-8f97-baae03a1b74c.png)
