### ISSUE TITLE
Deploy System to Digital Ocean

### ISSUE THREAD

**Issue by buccatm** [campus-occupancy/campus-occupancy#6]
Please do work for this task in a branch named issue - 006.

- [x] Deploy Meteor application to Digital ocean 

- [x] Set up application performance monitoring for Meteor

**Comment by fredstraub** [comment]
Deployed the project to Digital Ocean.  URL is [164.90.146.203](http://164.90.146.203/#/)  Completed the other two parts of [E60](http://courses.ics.hawaii.edu/ics314f20/morea/deployment/experience-app-deployment-digital-ocean.html).  Shared the mup.js file on the class/group discord channel.

<img width="1542" alt="Screen Shot 2020-11-18 at 10 30 51 AM" src="https://user-images.githubusercontent.com/50086431/99612552-e30e8400-29b9-11eb-85ee-c9528c69339a.png">

<img width="1135" alt="correct-RoboT3-firstDeploy" src="https://user-images.githubusercontent.com/50086431/99612729-3f71a380-29ba-11eb-8bd2-f3cef3c683fe.png">

<img width="1832" alt="MontiAPM-firstDeployed" src="https://user-images.githubusercontent.com/50086431/99612746-45678480-29ba-11eb-83de-8a9655dee755.png">
