### ISSUE TITLE
Create Edit Data Page

### ISSUE THREAD

**Issue by buccatm** [campus-occupancy/campus-occupancy#7]
Please do work for this task in a branch called issue- 007.

- [x] Add a way to upload info

**Comment by fredstraub** [comment]
Created EditDataPage.  Added it to app.jsx with the URL **/edit.**  Ran lint and merged into Master.
<img width="1434" alt="EditDataPage" src="https://user-images.githubusercontent.com/50086431/99613066-efdfa780-29ba-11eb-8ce3-20429706d032.png">
<img width="1427" alt="EditData-files-change" src="https://user-images.githubusercontent.com/50086431/99613083-fb32d300-29ba-11eb-834c-dc9576eac5cd.png">
<img width="1115" alt="Screen Shot 2020-11-17 at 4 13 39 PM" src="https://user-images.githubusercontent.com/50086431/99613167-27e6ea80-29bb-11eb-8e23-b9f3f4b349e7.png">
<img width="1550" alt="ESLint-on-EditDataPage" src="https://user-images.githubusercontent.com/50086431/99613096-0259e100-29bb-11eb-9575-276ad73cc19c.png">
