### ISSUE TITLE
Create Data Page

### ISSUE THREAD

**Issue by buccatm** [campus-occupancy/campus-occupancy#8]
Please do work for this task in a branch called issue- 008.

- [x] have the map be the background

- [x] add import 

- [x] add table form

**Comment by fredstraub** [comment]
Created new page DataPage.jsx.  Added it to app.jsx.  Ran lint to check the code.
<img width="1399" alt="Code changes-for-DataPage" src="https://user-images.githubusercontent.com/50086431/99613650-02a6ac00-29bc-11eb-80a7-14d655e105ba.png">

<img width="1550" alt="ES-lint-on-DataPage" src="https://user-images.githubusercontent.com/50086431/99613681-0df9d780-29bc-11eb-9874-583545982e18.png">
